### ISSUE TITLE
no antenna_logs group in pbo_data.h5

### ISSUE THREAD

**Issue by cgammans3** [MITHaystack/scikit-dataaccess#1]
I downloaded pbo using 
> skdaccess pbo

and got this error

>Traceback (most recent call last):
  File "/Users/cgammans/anaconda3/bin/skdaccess", line 11, in <module>
    sys.exit(skdaccess_script())
  File "/Users/cgammans/anaconda3/lib/python3.6/site-packages/skdaccess/bin/skdaccess.py", line 50, in skdaccess_script
    PBODF.downloadFullDataset(use_file=args.local_data)
  File "/Users/cgammans/anaconda3/lib/python3.6/site-packages/skdaccess/geo/pbo/data_fetcher.py", line 384, in downloadFullDataset
    anttext = zipfile.read('All_PBO_ants.eq').decode()
  File "/Users/cgammans/anaconda3/lib/python3.6/zipfile.py", line 1314, in read
    with self.open(name, "r", pwd) as fp:
  File "/Users/cgammans/anaconda3/lib/python3.6/zipfile.py", line 1352, in open
    zinfo = self.getinfo(name)
  File "/Users/cgammans/anaconda3/lib/python3.6/zipfile.py", line 1281, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'All_PBO_ants.eq' in the archive"

However, this file is in fact in the zip file.  

>ls
All_PBO_ants.eq                    MR_1996All.PBO_fin_COCNT.ps        MR_1996All.PBO_fin_hist_GAM.ps     cwu.snips_nam08.vel.20170821110312 pbo.snips_igs08.txt.20170821110312
All_PBO_eqs.eq                     MR_1996All.PBO_fin_EASTC.ps        MR_1996All.PBO_fin_hist_NUC.ps     nmt.snaps_nam08.vel.20170821110312 pbo.snips_igs08.vel.20170821110312
All_PBO_igs08.apr                  MR_1996All.PBO_fin_LABAS.ps        MR_1996All.PBO_fin_hist_PBO.ps     nmt.snips_nam08.txt.20170821110312 pbo.snips_nam08.ps
All_PBO_nam08.apr                  MR_1996All.PBO_fin_NCALF.ps        MR_1996All.PBO_fin_hist_USG.ps     nmt.snips_nam08.vel.20170821110312 pbo.snips_nam08.txt.20170821110312
All_PBO_unkn.eq                    MR_1996All.PBO_fin_WUSSC.ps        MR_2017_06.sum                     pbo.kalts_nam08.off                pbo.snips_nam08.vel.20170821110312
MR_1996All.PBO_fin_ALASK.ps        MR_1996All.PBO_fin_hist_COC.ps     cwu.snaps_nam08.vel.20170821110312 pbo.snaps_igs08.vel.20170821110312
MR_1996All.PBO_fin_CENTL.ps        MR_1996All.PBO_fin_hist_EXP.ps     cwu.snips_nam08.txt.20170821110312 pbo.snaps_nam08.vel.20170821110312

When I run the pbo example from the manual I get the error 
KeyError: 'No object named /antenna_logs in the file'

And when I look through the pbo_data.h5 file, it isn't there. All the data_[station] and meta_data groups are there though.

I've tried downloading the data a couple times and the first time I ran the skdaccess script the .skdaccess.conf update but the pbo header was [pbo.nams08.pos] which I changed to [pbo] for datafetcher to access and the pbo_data.h5 was missing from the data_location path.  I removed the pbo info from .skdaccess.conf and with subsequent download attempts, the file didn't update to include the data_location.

**Comment by CodyRude** [comment]
The structure of the zip file that contained the antenna swaps was changed. It was fixed on Github but not on pip. 

I've now updated it on pip so you should be able to upgrade the package now. Just in case, delete the downloaded files and the pbo_data.h5 file before running

 `skdaccess pbo`

**Comment by cgammans3** [comment]
I tried to upgrade but I'm now getting this error

>pip install scikit-dataaccess --upgrade
Collecting scikit-dataaccess
  Using cached https://files.pythonhosted.org/packages/bd/ab/47b952ebe4c44a00bad4cb68b360e94922101d70c49905ad68da9dbd70b6/scikit-dataaccess-1.9.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sp/5yjd5wwn6mb0wtc5kv928wmh000vs0/T/pip-install-2hmf_ayh/scikit-dataaccess/setup.py", line 9, in <module>
        with open("README.md") as rfile:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
>    ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sp/5yjd5wwn6mb0wtc5kv928wmh000vs0/T/pip-install-2hmf_ayh/scikit-dataaccess/

**Comment by CodyRude** [comment]
It was packaging the wrong README file. I fixed it, so you should be able to upgrade it now.

**Comment by cgammans3** [comment]
So I ended up uninstalling it and attempting to reinstall since I sometimes have issues upgrading. So now there is this error
>Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sp/5yjd5wwn6mb0wtc5kv928wmh000vs0/T/pip-install-aj458m11/GDAL/


Here is the full commandline output:
pip install scikit-dataaccess
Collecting scikit-dataaccess
  Using cached https://files.pythonhosted.org/packages/52/af/ca42257f3d7faa39118c3483aa3bb6b268388962d277d3fd9d1991327b1b/scikit-dataaccess-1.9.12.tar.gz
Requirement already satisfied: astropy>=1.1.0 in ./anaconda3/lib/python3.6/site-packages (from scikit-dataaccess) (2.0.2)
Requirement already satisfied: atomicwrites in ./anaconda3/lib/python3.6/site-packages (from scikit-dataaccess) (1.1.5)
Requirement already satisfied: geomag-algorithms in ./repos/geomag-algorithms (from scikit-dataaccess) (0.5.0)
Requirement already satisfied: ipython in ./anaconda3/lib/python3.6/site-packages (from scikit-dataaccess) (6.1.0)
Requirement already satisfied: ipywidgets in ./anaconda3/lib/python3.6/site-packages (from scikit-dataaccess) (7.0.0)
Requirement already satisfied: matplotlib in ./anaconda3/lib/python3.6/site-packages (from scikit-dataaccess) (2.0.2)
Requirement already satisfied: netCDF4 in ./anaconda3/lib/python3.6/site-packages (from scikit-dataaccess) (1.4.0)
Collecting GDAL (from scikit-dataaccess)
  Using cached https://files.pythonhosted.org/packages/78/90/d1039b76c4f81b0f94fdcc29f755d8de031a2fa0d31f06e8ad304b6f0b3f/GDAL-2.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/GDAL.egg-info
    writing pip-egg-info/GDAL.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/GDAL.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/GDAL.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/GDAL.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "/private/var/folders/sp/5yjd5wwn6mb0wtc5kv928wmh000vs0/T/pip-install-aj458m11/GDAL/setup.py", line 153, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/Users/cgammans/anaconda3/lib/python3.6/subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "/Users/cgammans/anaconda3/lib/python3.6/subprocess.py", line 1333, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: '../../apps/gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/sp/5yjd5wwn6mb0wtc5kv928wmh000vs0/T/pip-install-aj458m11/GDAL/setup.py", line 240, in get_gdal_config
        return fetch_config(option, gdal_config=self.gdal_config)
      File "/private/var/folders/sp/5yjd5wwn6mb0wtc5kv928wmh000vs0/T/pip-install-aj458m11/GDAL/setup.py", line 157, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: '../../apps/gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/sp/5yjd5wwn6mb0wtc5kv928wmh000vs0/T/pip-install-aj458m11/GDAL/setup.py", line 153, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/Users/cgammans/anaconda3/lib/python3.6/subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "/Users/cgammans/anaconda3/lib/python3.6/subprocess.py", line 1333, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sp/5yjd5wwn6mb0wtc5kv928wmh000vs0/T/pip-install-aj458m11/GDAL/setup.py", line 435, in <module>
        setup(**setup_kwargs)
      File "/Users/cgammans/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/cgammans/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/cgammans/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/cgammans/anaconda3/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 280, in run
        self.find_sources()
      File "/Users/cgammans/anaconda3/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 295, in find_sources
        mm.run()
      File "/Users/cgammans/anaconda3/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 526, in run
        self.add_defaults()
      File "/Users/cgammans/anaconda3/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 562, in add_defaults
        sdist.add_defaults(self)
      File "/Users/cgammans/anaconda3/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/Users/cgammans/anaconda3/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/Users/cgammans/anaconda3/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/Users/cgammans/anaconda3/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/sp/5yjd5wwn6mb0wtc5kv928wmh000vs0/T/pip-install-aj458m11/GDAL/setup.py", line 290, in finalize_options
        self.gdaldir = self.get_gdal_config('prefix')
      File "/private/var/folders/sp/5yjd5wwn6mb0wtc5kv928wmh000vs0/T/pip-install-aj458m11/GDAL/setup.py", line 246, in get_gdal_config
        return fetch_config(option)
      File "/private/var/folders/sp/5yjd5wwn6mb0wtc5kv928wmh000vs0/T/pip-install-aj458m11/GDAL/setup.py", line 157, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sp/5yjd5wwn6mb0wtc5kv928wmh000vs0/T/pip-install-aj458m11/GDAL/

**Comment by CodyRude** [comment]
This error is because it cannot find GDAL. Can you install gdal using conda?

**Comment by cgammans3** [comment]
I installed gdal, reinstalled scikit-dataaccess and downloaded the pbo data.  The conf file updated appropriately and I was able to access the data using the demo script provided.  

Thanks a lot for helping me out.  While I'm here I had an issue on the initial install with geomag-algorithms.  Their install isn't working quite right and I had to download their zip file then unzip and pip install -e in order to get that package.  I realize this isn't your problem but thought I would let you know that was a thing while I was here.

Again, Thanks so much!

**Comment by CodyRude** [comment]
> I installed gdal, reinstalled scikit-dataaccess and downloaded the pbo data. The conf file updated appropriately and I was able to access the data using the demo script provided.,

Excellent, glad to hear its working now. 

> Thanks a lot for helping me out. While I'm here I had an issue on the initial install with geomag-algorithms. Their install isn't working quite right and I had to download their zip file then unzip and pip install -e in order to get that package. I realize this isn't your problem but thought I would let you know that was a thing while I was here.

Thanks for the feedback, installing all the different scientific packages for python can get difficult.
